### ISSUE TITLE
shortcut for highlighting current focussed window

### ISSUE THREAD

**Issue by mipmip** [mipmip/gnome-shell-extensions-highlight-focus#2]

**Comment by rubaboo** [comment]
I would love an option to keep the border visible permanently, even when a window is maximized. Very helpful when having multiple displays. Also, the extension works with v42 as is, you might want to add that to json. Finally, I had to change the inset to zero after setting border-width to 2px. Otherwise the border was entirely outside the display boundaries when a window is maximized.

**Comment by mipmip** [comment]
Thanks for your feedback. Please submit separate issues and you might want to prepare a pull request for your last comment.
